In [13]:
# using JSON

In [14]:
import JSON

In [21]:
? JSON.parse

No documentation found.

`JSON.Parser.parse` is a `Function`.

```
# 2 methods for generic function "parse":
[1] parse(str::AbstractString; dicttype, inttype) in JSON.Parser at /Users/Harrison/.julia/packages/JSON/Hs3Dj/src/Parser.jl:390
[2] parse(io::IO; dicttype, inttype) in JSON.Parser at /Users/Harrison/.julia/packages/JSON/Hs3Dj/src/Parser.jl:403
```


In [15]:
? JSON.Parser.parsefile

No documentation found.

`JSON.Parser.parsefile` is a `Function`.

```
# 1 method for generic function "parsefile":
[1] parsefile(filename::AbstractString; dicttype, inttype, use_mmap) in JSON.Parser at /Users/Harrison/.julia/packages/JSON/Hs3Dj/src/Parser.jl:412
```


UndefVarError: UndefVarError: ls not defined

In [35]:
reaction_edges = JSON.parsefile("../jgi/reaction_edges_SAFR-032.json")


Dict{String,Any} with 2 entries:
  "substrates" => Dict{String,Any}("R02250"=>Any["C00422", "C00001"],"R09932"=>…
  "products"   => Dict{String,Any}("R02250"=>Any["C00641", "C00162"],"R09932"=>…

In [36]:
for k in reaction_edges
    println(typeof(k))
end

Pair{String,Any}
Pair{String,Any}


In [37]:
typeof(reaction_edges["products"])

Dict{String,Any}

In [38]:
typeof(reaction_edges["products"]["R03857"])

KeyError: KeyError: key "R03857" not found

In [39]:
reaction_edges

Dict{String,Any} with 2 entries:
  "substrates" => Dict{String,Any}("R02250"=>Any["C00422", "C00001"],"R09932"=>…
  "products"   => Dict{String,Any}("R02250"=>Any["C00641", "C00162"],"R09932"=>…

In [56]:
length(reaction_edges["products"])

1325

In [62]:
reaction_edges["products"]["R02250"]

2-element Array{Any,1}:
 "C00641"
 "C00162"

## Cleaned up code

In [215]:
reaction_edges = JSON.parsefile("../jgi/reaction_edges_SAFR-032.json")
seed_compounds = JSON.parsefile("../seeds/Freilich09.json");

In [219]:
reactions = [i for i in keys(reaction_edges["products"])] ## could use ["substates""] too

cpd_reactants_flat = unique(Iterators.flatten(values(reaction_edges["substrates"])))
cpd_products_flat = unique(Iterators.flatten(values(reaction_edges["products"])))
compounds = unique(Iterators.flatten([cpd_reactants_flat,cpd_products_flat]));


In [185]:
## For R and P:
## Reactons in columns
## Compounds in rows
## Rows, Columns
## This is equivilent to R and P in segrelab's github
# R = BitArray(undef, (length(reaction_dict),length(compound_dict)))
R = zeros(Int, (length(compounds),length(reactions)))
P = zeros(Int, (length(compounds),length(reactions)));

In [ ]:
for (i,r) in enumerate(reactions):
    R[:,i] = [Int(cpd in reaction_edges["substrates"][r]) for cpd in compounds]
    P[:,i] = [Int(cpd in reaction_edges["products"][r]) for cpd in compounds]
    

In [186]:
# for (r,col) in reaction_dict
#     for cpd_reactant in reaction_edges["substrates"][r]
#         R_row = compound_dict[cpd_reactant] # get row of compound
#         R[R_row,col] = 1 # compound is present
#     end
    
#     for cpd_product in reaction_edges["products"][r]
#         P_row = compound_dict[cpd_product] # get row of compound
#         P[P_row,col] = 1 # compound is present
        
#     end
# end

In [187]:
## Check to make sure R being populated correctly
length(collect(Iterators.flatten(cpd_reactants_nested)))==length(findall(R))


true

In [188]:
## Check to make sure P being populated correctly
length(collect(Iterators.flatten(cpd_products_nested)))==length(findall(P))


true

### Organism specific seeds

In [192]:
length(intersect(keys(seed_compounds),compounds))

59

In [193]:
length(keys(seed_compounds))

65

In [198]:
org_seed = collect(intersect(keys(seed_compounds),compounds));

In [210]:
binary_org_seed = [Int(i in org_seed) for i in compounds];

## Even better code

In [407]:
reaction_edges = JSON.parsefile("../kegg/2018-09-25/reaction_edges.json");

In [408]:
reactions = [i for i in keys(reaction_edges["products"])] ## could use ["substrates""] too

cpd_reactants_flat = unique(Iterators.flatten(values(reaction_edges["substrates"])))
cpd_products_flat = unique(Iterators.flatten(values(reaction_edges["products"])))
compounds = unique(Iterators.flatten([cpd_reactants_flat,cpd_products_flat]));


#### R and P: Reactant and Product matrices

In [409]:
## For R and P:
## Reactons in columns
## Compounds in rows
## Rows, Columns
## This is equivilent to R and P in segrelab's github
# R = BitArray(undef, (length(reaction_dict),length(compound_dict)))
R = zeros(Int, (length(compounds),length(reactions)))
P = zeros(Int, (length(compounds),length(reactions)));

** Below loop takes about a minute to run when using all of KEGG **

In [410]:
for (i,r) in enumerate(reactions)
    R[:,i] = [Int(cpd in reaction_edges["substrates"][r]) for cpd in compounds]
    P[:,i] = [Int(cpd in reaction_edges["products"][r]) for cpd in compounds]
end

In [411]:
R

8279×10287 Array{Int64,2}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  0  0  0  0  0  0  0  1  0     0  0  0  0  0  0  0  0  0  0  1  1
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  1  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0     0  0  0  1  0  1  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  1     0  0  0  1  0  0  0  0  0  0  1  0
 0  0  0  0  1  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  

In [412]:
## Check to make sure R being populated correctly
# length(collect(Iterators.flatten(values(reaction_edges["substrates"]))))==length(findall(R))


In [413]:
## Check to make sure P being populated correctly
# length(collect(Iterators.flatten(values(reaction_edges["products"]))))==length(findall(P))


#### x: seed compounds vector

In [433]:
# seed_compounds = JSON.parsefile("../seeds.json");
# x = [Int(i in seed_compounds["Enceladus_20-SAFR-032"]) for i in compounds];

ds80_seeds = ["C00011",
"C20298",
"C14819",
"C00087",
"C00237",
"C00058",
"C00033",
"C00031",
"C00095",
"C00124",
"C00159",
"C00243",
"C00208",
"C00282",
"C00007",
"C00001"]

ds90_seeds = ["C00031","C00001"]

x = [Int(i in ds80_seeds) for i in compounds];


In [434]:
# x

#### b: total number reactants vector (This is now defined within netexp)

In [435]:
# RT = transpose(R);
# b = [sum(RT[i,:]) for i in 1:size(RT)[1]];

#### t: target compounds vector

In [436]:
target_compounds = JSON.parsefile("../targets/Freilich09.json");
target_compounds_org = collect(intersect(keys(target_compounds),compounds));
t = [Int(i in target_compounds_org) for i in compounds];

In [437]:
# x

In [438]:
# TEST = []#Array{Int,2}([])
# x = [1,2,2,4]
# push!(TEST,x)
# push!(TEST,x)

In [439]:
# TEST[]

In [440]:
# sum(x)

## Make the network expansion loop!!!

In [441]:
function netexp(R::Array{Int,2},P::Array{Int,2},x::Array{Int,1})
    
    # initialize variables:
    # find the total number of metabolites in the seed set
    k = sum(x);
    # initialize previous iteration count of metabolites in the network
    k0 = 0;
    # iteration 1 consistes of the seed set
    X = []
    push!(X,x)  ## Each row is 1 generation
    # initialize reaction accumulation matrix
    Y = [];
    
    # transpose R
    RT = transpose(R)
    
    b = [sum(RT[i,:]) for i in 1:size(RT)[1]];

    # while the metabolite set has not converged
    while k > k0 
        
        # update previous number of metabolites
        k0 = k;
        
        # RT*x ==> represnts the number of present metabolites in the 
        # network within each reaction; if this isequal to the total 
        # number of metabolites in each reaction, then the reaction 
        # is added to the network
        y = Array{Int}(RT * x .== b)

        # P*y > 0 ==> represents the vector of reactions that produce 
        # metabolite i. (i in 1:m).  If this is >0, 
        # then that metabolite is producable 
        xnew = Array{Int}(P * y .> 0)
        
        #add to previous set of meatabolites (only needed to retain seed set)
        x = x .| xnew
        
        # find new total number of metabolites in network
        k = sum(x);

        # append accumulation matricies
        push!(X,x)
        push!(Y,y)
    
    end
    (X,Y)
end
    

netexp (generic function with 2 methods)

In [442]:
(X,Y) = netexp(R,P,x)

(Any[[0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], Any[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [443]:
size(X)

(8,)

In [444]:
size(Y)

(7,)

In [446]:
X

8-element Array{Any,1}:
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [448]:
sum(X[1])

15

In [425]:
# unique([Y[1][i]==1 ? reactions[i] : "SKIP" for (i,r) in enumerate(reactions)])


In [426]:
length(reactions)

10287

In [427]:
length(compounds)

8279

In [428]:
reactions_by_generation = Dict()
for j in 1:size(Y)[1]
    reactions_by_generation[j] = []
    for (i,r) in enumerate(reactions)
        if Y[j][i]==1
            push!(reactions_by_generation[j],reactions[i])
        end
    end
end

In [429]:
compounds_by_generation = Dict()
for j in 1:size(X)[1]
    compounds_by_generation[j] = []
    for (i,c) in enumerate(compounds)
        if X[j][i]==1
            push!(compounds_by_generation[j],compounds[i])
        end
    end
end

In [430]:
reactions_by_generation

Dict{Any,Any} with 7 entries:
  7 => Any["R08570", "R02991", "R05539", "R00307", "R00816", "R02763", "R07803"…
  4 => Any["R08570", "R05539", "R00307", "R00816", "R02763", "R07803", "R01100"…
  2 => Any["R05539", "R00307", "R07803", "R01100", "R00276", "R00302", "R00533"…
  3 => Any["R05539", "R00307", "R00816", "R07803", "R01100", "R00276", "R00302"…
  5 => Any["R08570", "R05539", "R00307", "R00816", "R02763", "R07803", "R01100"…
  6 => Any["R08570", "R02991", "R05539", "R00307", "R00816", "R02763", "R07803"…
  1 => Any["R05539", "R00307", "R01100", "R00302", "R01098", "R00874", "R00028"…

In [431]:
compounds_by_generation

Dict{Any,Any} with 8 entries:
  7 => Any["C00001", "C00007", "C00094", "C00124", "C00022", "C00204", "C00027"…
  4 => Any["C00001", "C00007", "C00094", "C00124", "C00022", "C00204", "C00027"…
  2 => Any["C00001", "C00007", "C00094", "C00124", "C00027", "C00033", "C00794"…
  3 => Any["C00001", "C00007", "C00094", "C00124", "C00027", "C00033", "C00794"…
  5 => Any["C00001", "C00007", "C00094", "C00124", "C00022", "C00204", "C00027"…
  8 => Any["C00001", "C00007", "C00094", "C00124", "C00022", "C00204", "C00027"…
  6 => Any["C00001", "C00007", "C00094", "C00124", "C00022", "C00204", "C00027"…
  1 => Any["C00001", "C00007", "C00124", "C00033", "C00011", "C00031", "C00095"…

In [87]:
reaction_values = [i[1] for i in reaction_edges["products"]]

1325-element Array{String,1}:
 "R02250"
 "R09932"
 "R01876"
 "R02331"
 "R08218"
 "R06983"
 "R07043"
 "R04800"
 "R10849"
 "R08281"
 "R04273"
 "R04945"
 "R09407"
 ⋮       
 "R09442"
 "R02926"
 "R07140"
 "R00939"
 "R10088"
 "R05051"
 "R01135"
 "R10917"
 "R03509"
 "R00416"
 "R05233"
 "R06728"

In [71]:
compound_values = [i[2] for i in reaction_edges["products"]]

1325-element Array{Array{Any,1},1}:
 ["C00641", "C00162"]          
 ["C20226", "C00005", "C00080"]
 ["C00106", "C00620"]          
 ["C00008", "C00460"]          
 ["C00020", "C00013", "C06481"]
 ["C01031", "C00004", "C00080"]
 ["C14813"]                    
 ["C00001", "C05432", "C00028"]
 ["C00641", "C20897"]          
 ["C16551", "C00003"]          
 ["C03633"]                    
 ["C05699", "C00033"]          
 ["C19595", "C00001", "C00006"]
 ⋮                             
 ["C19604", "C00001", "C00006"]
 ["C00794", "C00124"]          
 ["C01031", "C00005", "C00080"]
 ["C00415", "C00005", "C00080"]
 ["C00001", "C00018", "C00009"]
 ["C05938", "C00003", "C00001"]
 ["C00035", "C00009", "C03794"]
 ["C20941", "C00004", "C00080"]
 ["C01302"]                    
 ["C00013", "C00043"]          
 ["C06613", "C00004", "C00080"]
 ["C12448", "C00180"]          

In [75]:
length(Set(collect(Iterators.flatten(compound_values))))

948

In [79]:
length(unique(collect(Iterators.flatten(compound_values))))

948

In [80]:
unique(collect(Iterators.flatten(compound_values)))

948-element Array{Any,1}:
 "C00641"
 "C00162"
 "C20226"
 "C00005"
 "C00080"
 "C00106"
 "C00620"
 "C00008"
 "C00460"
 "C00020"
 "C00013"
 "C06481"
 "C01031"
 ⋮       
 "C05272"
 "C02659"
 "C16639"
 "C19604"
 "C00794"
 "C05938"
 "C03794"
 "C20941"
 "C01302"
 "C00043"
 "C06613"
 "C12448"

In [89]:
typeof(reaction_values)

Array{String,1}

In [93]:
compound_list = Array{String}(unique(collect(Iterators.flatten(compound_values))))


948-element Array{String,1}:
 "C00641"
 "C00162"
 "C20226"
 "C00005"
 "C00080"
 "C00106"
 "C00620"
 "C00008"
 "C00460"
 "C00020"
 "C00013"
 "C06481"
 "C01031"
 ⋮       
 "C05272"
 "C02659"
 "C16639"
 "C19604"
 "C00794"
 "C05938"
 "C03794"
 "C20941"
 "C01302"
 "C00043"
 "C06613"
 "C12448"

In [82]:
compound_dict = Dict()
for (i, compound) in enumerate(compound_list)
    compound_dict[compound] = i
end

In [83]:
compound_dict

Dict{Any,Any} with 948 entries:
  "C00334" => 141
  "C21017" => 832
  "C05691" => 599
  "C00508" => 456
  "C00093" => 165
  "C00001" => 16
  "C19595" => 25
  "C06506" => 496
  "C00396" => 581
  "C05273" => 321
  "C00279" => 176
  "C01165" => 532
  "C00068" => 48
  "C09332" => 890
  "C00080" => 5
  "C04160" => 560
  "C01352" => 792
  "C06174" => 879
  "C20969" => 793
  "C05141" => 637
  "C05539" => 863
  "C04810" => 88
  "C00489" => 104
  "C00344" => 263
  "C04734" => 440
  ⋮        => ⋮

In [95]:
reaction_dict = Dict()
for (i, reaction) in enumerate(reaction_values)
    reaction_dict[reaction] = i
end

In [111]:
reaction_dict

Dict{Any,Any} with 1325 entries:
  "R02250" => 1
  "R09932" => 2
  "R01876" => 3
  "R02331" => 4
  "R08218" => 5
  "R07043" => 7
  "R06983" => 6
  "R04800" => 8
  "R10849" => 9
  "R08281" => 10
  "R04273" => 11
  "R04945" => 12
  "R09407" => 13
  "R02788" => 14
  "R07607" => 15
  "R10223" => 16
  "R07650" => 17
  "R04383" => 18
  "R10645" => 19
  "R01859" => 20
  "R02426" => 21
  "R05681" => 22
  "R02718" => 23
  "R01072" => 24
  "R02688" => 25
  ⋮        => ⋮

In [107]:
BitArray(undef, (3,2))

3×2 BitArray{2}:
 false  false
 false  false
 false  false

In [136]:
Z =  zeros(Bool, (3,2))

3×2 Array{Bool,2}:
 false  false
 false  false
 false  false

In [139]:
Z[1,1]=true

true

In [140]:
Z

3×2 Array{Bool,2}:
  true  false
 false  false
 false  false

In [108]:
## Compounds in columns
## Reactions in rows
## Rows, Columns
## This is equivilent to R` in segrelab's github
# R = BitArray(undef, (length(reaction_dict),length(compound_dict)))
R = zeros(Bool, (length(reaction_dict),length(compound_dict)))

1325×948 Array{Bool,2}:
 false  false  false  false  false  …  false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false  …  false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false  …  false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
 false  false  false  false  false     false  false  false  false  false
     ⋮                     

In [117]:
for (r,rindex) in reaction_dict
    println(k)
    println(v)
#     reaction_dict[r]
    break
end

R02250
1
